package data_access_objects;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import data_structures.Course;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

/**
 * Data Accessing Object for our Course table. Handling our create, update, delete operations.
 */
public class CourseDAO {
	/** An instance of Connection for accessing the database*/
	private Connection conn = MySQLConnection.getConnection();
	
    /**
     * Creates a new course record in the database.
     *
     * @param course_name	The name of the course.
     * @param instructor	The instructor of the course.
     * @param semester		The semester the course is offered.
     * @return				A Course object representing the newly created record, or null if creation failed.
     */
	
	public Course createCourseRecord(String course_name, String instructor, String semester) {
		int id = -1;
		String sql = String.format("INSERT INTO Courses "
				+ "(course_name, instructor, semester) "
				+ "VALUES ('%s', '%s', '%s');", course_name, instructor, semester);
		
		try {
			Statement stmt = conn.createStatement();
            int rowsAffected = stmt.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);

            // If a record was inserted, retrieve the autogenerated courseID
            if (rowsAffected > 0) {
                ResultSet generatedKeys = stmt.getGeneratedKeys();
                if (generatedKeys.next()) {
                    id = generatedKeys.getInt(1);  // Set the id to the autogenerated courseID
                    System.out.println("Course record created with ID: " + id);
                }
            }
            return new Course(id, course_name, instructor, semester);
		}
		catch (SQLException e) {
			e.printStackTrace();
		}
		
		return null;
	}
	
    /**
     * Deletes a course record from the database by its ID.
     *
     * @param	id The ID of the course to delete.
     */
	
	public void deleteCourseRecord(int id) {
		String sql = String.format("DELETE FROM Courses "
				+ " WHERE courseID = %d;", id);
		
		try {
			Statement stmt = conn.createStatement();
			stmt.executeUpdate(sql);
			System.out.println("Course record deleted.");
			stmt.close();
		}
		catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
	
    /**
     * Updates an existing course record in the database.
     *
     * @param id			The ID of the course to update.
     * @param course_name	The new course name.
     * @param instructor	The new instructor name.
     * @param semester		The new semester.
     */
	
	public void updateCourseRecord(int id, String course_name, String instructor, String semester) {
	    // Use String.format() correctly, ensuring %s for string parameters and %d for the ID
	    String sql = String.format("UPDATE Courses "
	            + "SET course_name = '%s', instructor = '%s', semester = '%s' "
	            + "WHERE courseID = %d;", course_name, instructor, semester, id);
	    
	    try {
	        Statement stmt = conn.createStatement();
	        stmt.executeUpdate(sql);
	        stmt.close();
	    }
	    catch (SQLException e) {
	        e.printStackTrace();
	    }
	}
	
    /**
     * Searches for course records based on specified columns and conditions.
     *
     * @param cols	The columns to select.
     * @param cond	The condition for selection.
     * @return		A list of Course objects matching the search criteria.
     */
	public List<Course> searchCourseRecord(String cols, String cond) {
	    List<Course> results = new ArrayList<>();
	    String sql = String.format("SELECT %s FROM Courses", cols);
	    if (!cond.isEmpty()) {
	        sql += " WHERE " + cond;
	    }

	    // Debugging output
	    System.out.println(sql);

	    // Checking which fields are included
	    String lowerCols = cols.toLowerCase().replaceAll("\\s+", "");
	    boolean hasCourseID = lowerCols.contains("courseid") || lowerCols.equals("*");
	    boolean hasCourseName = lowerCols.contains("course_name") || lowerCols.equals("*");
	    boolean hasInstructor = lowerCols.contains("instructor") || lowerCols.equals("*");
	    boolean hasSemester = lowerCols.contains("semester") || lowerCols.equals("*");

	    try {
	        Statement stmt = conn.createStatement();
	        ResultSet rs = stmt.executeQuery(sql);

	        while (rs.next()) {
	            int id = hasCourseID ? rs.getInt("courseID") : -1;
	            String courseName = hasCourseName ? rs.getString("course_name") : null;
	            String instructor = hasInstructor ? rs.getString("instructor") : null;
	            String semester = hasSemester ? rs.getString("semester") : null;

	            Course course = new Course(id, courseName, instructor, semester);
	            results.add(course);
	        }

	        rs.close();
	        stmt.close();
	    } catch (SQLException e) {
	        e.printStackTrace();
	    }

	    return results;
	}

    /**
     * Fetches all course records from the database.
     *
     * @return	An ObservableList of all Course objects in the database.
     */
	
	public static ObservableList<Course> fetchAllCourses() {
	    ObservableList<Course> courseList = FXCollections.observableArrayList();
	    String sql = "SELECT * FROM Courses"; // Update this table name if needed

	    try (Connection conn = MySQLConnection.getConnection();
	         Statement stmt = conn.createStatement();
	         ResultSet rs = stmt.executeQuery(sql)) {

	        while (rs.next()) {
	        	int id = rs.getInt("courseID");
	            String courseName = rs.getString("course_name");
	            String instructor = rs.getString("instructor");
	            String semester = rs.getString("semester");

	            Course course = new Course(id, courseName, instructor, semester);
	            courseList.add(course);
	        }

	    } catch (SQLException e) {
	        e.printStackTrace();
	    }

	    return courseList;
	}
}
