package data_access_objects;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

public class CourseDAO {
	// An instance of Connection for accessing the database
	private Connection conn = MySQLConnection.getConnection();
	private String course;
	private String teacher;
	private String semester;
	private int id;

	public CourseDAO(int id, String course, String teacher, String semester) {
		this.id = id;
		this.course = course;
		this.teacher = teacher;
		this.semester = semester;
	}

	public CourseDAO(int id) {
		// TODO Auto-generated constructor stub
		this.id = id;
	}
	
	public void createCourseRecord(String course_name, String instructor, String semester) {
		String sql = String.format("INSERT INTO Courses "
				+ "(course_name, instructor, semester) "
				+ "VALUES ('%s', '%s', '%s');", course_name, instructor, semester);
		
		try {
			Statement stmt = conn.createStatement();
            int rowsAffected = stmt.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);

            // If a record was inserted, retrieve the autogenerated courseID
            if (rowsAffected > 0) {
                ResultSet generatedKeys = stmt.getGeneratedKeys();
                if (generatedKeys.next()) {
                    this.id = generatedKeys.getInt(1);  // Set the id to the autogenerated courseID
                    System.out.println("Course record created with ID: " + this.id);
                }
            }
		}
		catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
	
	public void deleteCourseRecord(int id) {
		String sql = String.format("DELETE FROM Courses "
				+ " WHERE courseID = %d;", id);
		
		try {
			Statement stmt = conn.createStatement();
			stmt.executeUpdate(sql);
			System.out.println("Course record deleted.");
			stmt.close();
		}
		catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
	
	public void updateCourseRecord(int id, String course_name, String instructor, String semester) {
	    // Use String.format() correctly, ensuring %s for string parameters and %d for the ID
	    String sql = String.format("UPDATE Courses "
	            + "SET course_name = '%s', instructor = '%s', semester = '%s' "
	            + "WHERE courseID = %d;", course_name, instructor, semester, id);
	    
	    try {
	        Statement stmt = conn.createStatement();
	        stmt.executeUpdate(sql);
	        stmt.close();
	    }
	    catch (SQLException e) {
	        e.printStackTrace();
	    }
	}
	
	/**
	 * @param cols		The columns we are searching for in the database (such as courseID)
	 * @param cond		The conditions (such as "course_name = 'Math', instructor = 'Smith'")
	 */
	public List<CourseDAO> searchCourseRecord(String cols, String cond) {
	    List<CourseDAO> results = new ArrayList<>();
	    String sql = String.format("SELECT %s FROM Courses", cols);
	    if (!cond.isEmpty()) {
	        sql += " WHERE " + cond;
	    }

	    // Debugging output
	    System.out.println(sql);

	    String lowerCols = cols.toLowerCase().replaceAll("\\s+", "");
	    boolean hasCourseID = lowerCols.contains("courseid") || lowerCols.equals("*");
	    boolean hasCourseName = lowerCols.contains("course_name") || lowerCols.equals("*");
	    boolean hasInstructor = lowerCols.contains("instructor") || lowerCols.equals("*");
	    boolean hasSemester = lowerCols.contains("semester") || lowerCols.equals("*");

	    try {
	        Statement stmt = conn.createStatement();
	        ResultSet rs = stmt.executeQuery(sql);

	        while (rs.next()) {
	            int id = hasCourseID ? rs.getInt("courseID") : -1;
	            String courseName = hasCourseName ? rs.getString("course_name") : null;
	            String instructor = hasInstructor ? rs.getString("instructor") : null;
	            String semester = hasSemester ? rs.getString("semester") : null;

	            CourseDAO course = new CourseDAO(id, courseName, instructor, semester);
	            results.add(course);
	        }

	        rs.close();
	        stmt.close();
	    } catch (SQLException e) {
	        e.printStackTrace();
	    }

	    return results;
	}

	public static ObservableList<CourseDAO> fetchAllCourses() {
	    ObservableList<CourseDAO> courseList = FXCollections.observableArrayList();
	    String sql = "SELECT * FROM Courses"; // Update this table name if needed

	    try (Connection conn = MySQLConnection.getConnection();
	         Statement stmt = conn.createStatement();
	         ResultSet rs = stmt.executeQuery(sql)) {

	        while (rs.next()) {
	        	int id = rs.getInt("courseID");
	            String courseName = rs.getString("course_name");
	            String instructor = rs.getString("instructor");
	            String semester = rs.getString("semester");

	            CourseDAO course = new CourseDAO(id, courseName, instructor, semester);
	            courseList.add(course);
	        }

	    } catch (SQLException e) {
	        e.printStackTrace();
	    }

	    return courseList;
	}
	
	public int getId() {
	    return id;
	}

	public String getCourseName() {
	    return course;
	}

	public String getInstructor() {
	    return teacher;
	}

	public String getSemester() {
	    return semester;
	}
}
